[package]
name = "reth-ethereum-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth dependencies
reth-cli.workspace = true
reth-cli-commands.workspace = true
reth-chainspec.workspace = true
reth-cli-runner.workspace = true
reth-db.workspace = true
reth-network.workspace = true
reth-node-builder.workspace = true
reth-node-ethereum.workspace = true
reth-node-core.workspace = true
reth-node-metrics.workspace = true
reth-tracing.workspace = true

# Miscellaneous dependencies
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true
tracing.workspace = true

# Async and utilities
tokio = { workspace = true, features = ["sync", "macros", "time", "rt-multi-thread"] }
futures.workspace = true

[features]
default = ["jemalloc", "reth-revm/portable"]

dev = ["reth-cli-commands/arbitrary"]

[dev-dependencies]
clap.workspace = true
reth-cli-commands.workspace = true
reth-ethereum-cli.workspace = true
tempfile.workspace = true
